[package]
name = "sc-consensus-poc-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "RPC extensions for the PoC consensus algorithm"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/substrate-node-template"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-consensus-poc = { version = "0.1.0", path = ".." }
sc-rpc-api = { version = "0.9.0", path = "../../../../../substrate/client/rpc-api" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
jsonrpc-pubsub = "15.1.0"
sp-consensus-poc = { version = "0.1.0", path = "../../../../primitives/consensus/poc" }
serde = { version = "1.0.104", features=["derive"] }
sp-blockchain = { version = "3.0.0", path = "../../../../../substrate/primitives/blockchain" }
sp-runtime = { version = "3.0.0", path = "../../../../../substrate/primitives/runtime" }
sc-consensus-epochs = { version = "0.9.0", path = "../../../../../substrate/client/consensus/epochs" }
futures = { version = "0.3.4", features = ["compat"] }
futures-timer = "3.0.2"
derive_more = "0.99.2"
sp-api = { version = "3.0.0", path = "../../../../../substrate/primitives/api" }
sp-consensus = { version = "0.9.0", path = "../../../../../substrate/primitives/consensus/common" }
sp-core = { version = "3.0.0", path = "../../../../../substrate/primitives/core" }
sp-application-crypto = { version = "3.0.0", path = "../../../../../substrate/primitives/application-crypto" }
sp-keystore = { version = "0.9.0", path = "../../../../../substrate/primitives/keystore" }
log = "0.4.14"
parking_lot = "0.11.1"

[dev-dependencies]
sc-consensus = { version = "0.9.0", path = "../../../../../substrate/client/consensus/common" }
serde_json = "1.0.50"
sp-keyring = { version = "3.0.0", path = "../../../../../substrate/primitives/keyring" }
sc-keystore = { version = "3.0.0", path = "../../../../../substrate/client/keystore" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../../../substrate/test-utils/runtime/client" }
tempfile = "3.1.0"
